#! /bin/perl

# Parse command-line switches
use Getopt::Std;
%opt = ();
getopts('qrth', \%opt);

$usage  = "multi [opts] cmd bef aft [files]\n";
$usage .= " -h      help; print this message\n";
$usage .= " -t      test-only; print commands and do nothing\n";
$usage .= " -q      quiet; execute commands but do not print\n";
if ($opt{h}) {
    print $usage;
    exit;
}

$cmd   = shift @ARGV;
$befor = shift @ARGV;
$after = shift @ARGV;

unless (defined($cmd) and defined($befor) and defined($after)) {
    print "Usage: multi cmd before_pat after_pat\n";
    exit(1);
}

@oldfiles = (@ARGV > 0 ? 
	     @ARGV     :
	     glob("*$befor*"));

foreach $old (@oldfiles) {
    chomp $old;
    ($new = $old) =~ s/$befor/$after/;
    $redirect = "> "                        if $opt{r};
    $old =~ s!(\W)!\\$1!g;
    $new =~ s!(\W)!\\$1!g;
    $command = "$cmd $old $redirect$new";
    print "$command\n"                  unless $opt{q};
    system($command)                    unless $opt{t};
}
